name: "Bug Report"
description: "Report a bug you encountered in the project"
labels: ["bug"]

# Fields to display in the form
fields:
  - type: textarea
    label: "Describe the bug"
    description: "A clear and concise description of what the bug is."
    required: true
  - type: textarea
    label: "Steps to reproduce"
    description: "Provide a step-by-step description of how to reproduce the bug."
    required: true
  - type: text
    label: "Expected Behavior"
    description: "Describe what you expected to happen."
    required: false
  - type: text
    label: "Actual Behavior"
    description: "Describe what actually happened."
    required: false
  - type: dropdown
    label: "Priority"
    options:
      - "High"
      - "Medium"
      - "Low"
    description: "Select the priority level of this bug."
    required: true
