# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

# Templates Configuration
templates:
  bug_report:
    name: "Bug Report"
    description: "Use this template to report a bug or unexpected behavior."
    labels:
      - "bug"
    template: "bug_report.md"
    # Custom instructions for the title when creating a bug report issue.
    title: "Please provide a short and descriptive title for the bug"
    # Default assignees for bug reports (optional).
    assignees:
      - "@teamA"

  feature_request:
    name: "Feature Request"
    description: "Suggest a new feature or improvement for the project."
    labels:
      - "enhancement"
    template: "feature_request.md"
    title: "Please provide a clear title for your feature request"
    assignees:
      - "@teamB"
    # Optional: Set additional reviewers or maintainers for feature requests.
    reviewers:
      - "@devTeam"

  general_issue:
    name: "General Issue"
    description: "Create a general issue that doesn't fall under bug report or feature request."
    labels:
      - "question"
    template: "issue_template.md"
    title: "Please provide a clear description of the issue"
    assignees:
      - "@teamC"
    # Optional: Default reviewers for general issues.
    reviewers:
      - "@teamC"

  documentation:
    name: "Documentation Update"
    description: "Report an issue or suggest an update to the documentation."
    labels:
      - "documentation"
    template: "documentation_issue.md"
    title: "Please describe the documentation change or issue"
    assignees:
      - "@docsTeam"
    reviewers:
      - "@docsTeam"

# Default Labels (Optional) - Can be customized for all issues
default_labels:
  - "help wanted"
  - "good first issue"

# Optional: Automatically assign labels based on template type.
auto_labels:
  bug_report: 
    - "bug"
    - "high priority"
  feature_request:
    - "enhancement"
  general_issue:
    - "needs triage"
  documentation:
    - "documentation"

# Optional: Title and body customization for each template
# These are instructions displayed in the issue body when the template is applied.
body:
  bug_report: |
    ## Expected Behavior
    Please describe what you expected to happen.

    ## Actual Behavior
    Please describe what actually happened.

    ## Steps to Reproduce
    1. Step 1
    2. Step 2
    3. ...

    ## Additional Context
    Please provide any other details (logs, screenshots, environment info).

  feature_request: |
    ## Is your feature request related to a problem? Please describe.
    Provide context on the problem you're trying to solve.

    ## Describe the solution you'd like
    What solution or feature would you like to see implemented?

    ## Additional Context
    Any other relevant details or screenshots.

  general_issue: |
    ## Issue Description
    Provide a clear and concise description of the issue.

    ## Steps to Reproduce
    - Step 1
    - Step 2

    ## Expected Outcome
    What should happen?

    ## Actual Outcome
    What is happening?

    ## Additional Information
    Provide any extra information or context.

  documentation: |
    ## Documentation Issue
    Please describe the issue or change needed in the documentation.

    ## Steps to Reproduce (if applicable)
    1. Step 1
    2. Step 2

    ## Suggested Change
    What change would you like to see in the documentation?

    ## Additional Information
    Any other relevant information about the documentation issue.

# Optional: Issue Title Prefix (for consistency)
# This could be used to prompt users to follow a naming convention for issue titles.
title_prefix:
  bug_report: "BUG: "
  feature_request: "FEATURE: "
  general_issue: "ISSUE: "
  documentation: "DOC: "

# Optional: Template sorting order (this determines the order the templates will appear)
template_sort_order:
  - bug_report
  - feature_request
  - general_issue
  - documentation

# Optional: Provide some pre-filled checklists for common tasks (like testing)
checklist:
  bug_report: |
    - [ ] I have checked for similar issues or bugs.
    - [ ] I have verified the issue with the latest version of the project.
    - [ ] I have included relevant logs or error messages.
  
  feature_request: |
    - [ ] I have provided a clear and concise description of the feature.
    - [ ] I have described why this feature would be beneficial.
    - [ ] I have included any relevant use cases or user stories.

  general_issue: |
    - [ ] I have clearly described the issue and the expected outcome.
    - [ ] I have followed the issue reporting guidelines.

  documentation: |
    - [ ] I have described the documentation issue or change clearly.
    - [ ] I have suggested a possible solution to improve the documentation.


contact_links:
  - name: Contact NLTC 
    url: https://nltelugucommunity.org/contact-us/
    about: To connect with NLTC
  - name: Know more about NLTC 
    url: https://nltelugucommunity.org
    about: About NLTC
