# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

templates:
  - name: "Bug Report"
    description: "Report a bug you encountered in the project."
    template: "bug_report.yml"
  - name: "Feature Request"
    description: "Request a new feature or enhancement."
    template: "feature_request.yml"

contact_links:
  - name: Contact NLTC 
    url: https://nltelugucommunity.org/contact-us/
    about: To connect with NLTC
  - name: Know more about NLTC 
    url: https://nltelugucommunity.org
    about: About NLTC
