# .github/workflows/greet.yml
name: Greet Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Welcome to our project! Thank you for your contribution."
